import "./App.css";
import { useRef } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  Sparkles,
  OrbitControls,
  useGLTF,
  PositionalAudio,
} from "@react-three/drei";
import { Overlay } from "./Overlay.js";

export default function App({ ready }) {
  return (
    <>
      <Canvas dpr={[1, 2]} camera={{ position: [0, 5, 20], fov: 40 }}>
        <fog attach="fog" args={["#cc7b32", 0, 500]} />
        <OrbitControls />
        <ambientLight color="orange" intensity={1} />
        <Sparkles
          size={10}
          scale={[10, 10, 10]}
          position-y={1}
          speed={1}
          count={50}
        />
        <Model ready={ready} />
      </Canvas>
      <Overlay />
    </>
  );
}

function Model({ ready }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene-draco.glb");
  useFrame(() => (group.current.rotation.y += 0.0009));
  return (
    <group ref={group} scale={0.001} position={[0, -1, -50]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-102253.52, -210688.86, -17050.52]}>
          <mesh
            material={materials.Scene_Root}
            geometry={nodes.mesh_0.geometry}
          />
          <mesh
            material={materials.Scene_Root}
            geometry={nodes.mesh_1.geometry}
          />
          <mesh
            material={materials.Scene_Root}
            geometry={nodes.mesh_2.geometry}
          />
          <mesh
            material={materials.Scene_Root}
            geometry={nodes.mesh_3.geometry}
          />
        </group>
        <group position={[100000, 120000, 2000]} />
        <mesh position={[250000, -200000, 50000]}>
          <sphereGeometry args={[30000, 32, 32]} />
          <meshBasicMaterial color="#ffffff" />
        </mesh>
      </group>
    </group>
  );
}

/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: jemepousse (https://sketchfab.com/jemepousse)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/356c773c4b9a45d8b9d4aa04c60ecb27
title: Red City
*/
